---
title: "Puberty CFA + sMRI for TAG Wave 1"
author: "Michelle Byrne, Sam Chavez, Nandi Vijayakumar"
date: "Nov 13 2021"
output: html_document
---

## Set Working Directory
```{r Set Directory, message=FALSE, warning=FALSE, include=FALSE}
getwd()
#if not the first time running this script, load the workspace:
load("Z:/TAG/projects/W1_puberty_modelling/puberty_sMRI/Puberty_CFA_sMRI.RData")

#Otherwise work through code starting from here
#You should set this to the behavioral directory on the TAG file server 
workdir='Z:/TAG/behavior/' 
```

## Loading Libraries

```{r libraries, include = F}
library(tidyverse)
library(lavaan)
library(semPlot)
library(reshape2)
library(dplyr)
library(Hmisc)
library(corrplot)
library(lmtest)
library(nlsem)
```

## Load and Clean Data
```{r Load and Clean Data}
# Load Data. NOTE: The "PBIP" variables are not actually from the Picture Based Interview of Puberty (PBIP) but the Udry & Morris Line drawings, reported as LD1 and LD2 in the manuscript.
saliva <- read.csv(file.path(workdir,"Puberty/Saliva/Wave1/TAG_W1_Saliva_wide_cens_only4.csv", fsep=""))
hair <- read.csv(file.path(workdir,"Puberty/Hair/Wave1/TAG_W1_Hair_processed.csv", fsep=""))
qs <- read.csv(file.path(workdir,"Questionnaires/Puberty/Composite/TAG_W1_PubertyComposite.csv", fsep=""))
sMRI <- read.csv(file.path("Z:/TAG/projects/W1_puberty_modelling/puberty_sMRI/TAGsMRI_forCFAPuberty.csv", fsep=""))

# Reformat & Merge Data

# Transforming Hair Data into Wide Format
hair <- dcast(hair, SID ~ hormone, value.var = "concentration_ln")
colnames(hair) <- c("SID","dhea_hair","estr_hair","test_hair")

# Getting rid of Saliva clutter
sal_dhea <- select(saliva, "SID", "sal_DHEA_conc_ln_w_1", "sal_DHEA_conc_ln_w_2", 
               "sal_DHEA_conc_ln_w_3", "sal_DHEA_conc_ln_w_4")
colnames(sal_dhea) <- c("SID","dhea1","dhea2","dhea3","dhea4")
sal_estr <- select(saliva, "SID", "sal_EST_conc_ln_w_1", "sal_EST_conc_ln_w_2", 
               "sal_EST_conc_ln_w_3", "sal_EST_conc_ln_w_4")
colnames(sal_estr) <- c("SID","estr1","estr2","estr3","estr4")
sal_test <- select(saliva, "SID", "sal_TEST_conc_ln_w_1", "sal_TEST_conc_ln_w_2", 
               "sal_TEST_conc_ln_w_3", "sal_TEST_conc_ln_w_4")
colnames(sal_test) <- c("SID","test1","test2","test3","test4")

# Re-Merging Saliva Data
saliva <- sal_dhea %>% full_join(sal_estr, by = "SID") %>% full_join(sal_test, by = "SID")

# Getting rid of Questionnaire Clutter
sr_qs <- select(qs, "SID", "PDS_F1", "PDS_F2", "PDS_F3", 
                "PDS_F4", "PDS_F6", "PBIP_1A", "PBIP_2A")
colnames(sr_qs) <- c("SID","PDS1","PDS2","PDS3",
                     "PDS4","PDS6","PBIP1","PBIP2")

# Making one big pretty data frame
hormones <- saliva %>% full_join(hair, by = "SID")
hormones_complete_E2hair <- filter(hormones, !is.na(estr_hair))
data <- hormones %>% full_join(sr_qs, by = "SID")

# Count missing data by variable
missing <- data.frame(matrix(ncol = 44, nrow = 1))
colnames(missing) <- c("na_dhea1","percna_dhea1","na_dhea2","percna_dhea2","na_dhea3",
                       "percna_dhea3","na_dhea4","percna_dhea4","na_estr1","percna_estr1",
                       "na_estr2","percna_estr2","na_estr3","percna_estr3","na_estr4",
                       "percna_estr4","na_test1","percna_test1","na_test2","percna_test2",
                       "na_test3","percna_test3","na_test4","percna_test4","na_dhea_hair",
                       "percna_dhea_hair","na_estr_hair","percna_estr_hair",
                       "na_test_hair","percna_test_hair","na_PDS1","percna_PDS1",
                       "na_PDS2","percna_PDS2","na_PDS3","percna_PDS3","na_PDS4",
                       "percna_PDS4","na_PDS6","percna_PDS6","na_PBIP1","percna_PBIP1",
                       "na_PBIP2","percna_PBIP2")
missing$na_dhea1 <- length(data$dhea1)-length(na.omit(data$dhea1))
missing$percna_dhea1 <- (missing$na_dhea1/length(data$dhea1))*100
missing$na_dhea2 <- length(data$dhea2)-length(na.omit(data$dhea2))
missing$percna_dhea2 <- (missing$na_dhea2/length(data$dhea2))*100
missing$na_dhea3 <- length(data$dhea3)-length(na.omit(data$dhea3))
missing$percna_dhea3 <- (missing$na_dhea3/length(data$dhea3))*100
missing$na_dhea4 <- length(data$dhea4)-length(na.omit(data$dhea4))
missing$percna_dhea4 <- (missing$na_dhea4/length(data$dhea4))*100
missing$na_estr1 <- length(data$estr1)-length(na.omit(data$estr1))
missing$percna_estr1 <- (missing$na_estr1/length(data$estr1))*100
missing$na_estr2 <- length(data$estr2)-length(na.omit(data$estr2))
missing$percna_estr2 <- (missing$na_estr2/length(data$estr2))*100
missing$na_estr3 <- length(data$estr3)-length(na.omit(data$estr3))
missing$percna_estr3 <- (missing$na_estr3/length(data$estr3))*100
missing$na_estr4 <- length(data$estr4)-length(na.omit(data$estr4))
missing$percna_estr4 <- (missing$na_estr4/length(data$estr4))*100
missing$na_test1 <- length(data$test1)-length(na.omit(data$test1))
missing$percna_test1 <- (missing$na_test1/length(data$test1))*100
missing$na_test2 <- length(data$test2)-length(na.omit(data$test2))
missing$percna_test2 <- (missing$na_test2/length(data$test2))*100
missing$na_test3 <- length(data$test3)-length(na.omit(data$test3))
missing$percna_test3 <- (missing$na_test3/length(data$test3))*100
missing$na_test4 <- length(data$test4)-length(na.omit(data$test4))
missing$percna_test4 <- (missing$na_test4/length(data$test4))*100

missing$na_dhea_hair <- length(data$dhea_hair)-length(na.omit(data$dhea_hair))
missing$percna_dhea_hair <- (missing$na_dhea_hair/length(data$dhea_hair))*100
missing$na_estr_hair <- length(data$estr_hair)-length(na.omit(data$estr_hair))
missing$percna_estr_hair <- (missing$na_estr_hair/length(data$estr_hair))*100
missing$na_test_hair <- length(data$test_hair)-length(na.omit(data$test_hair))
missing$percna_test_hair <- (missing$na_test_hair/length(data$test_hair))*100

missing$na_PDS1 <- length(data$PDS1)-length(na.omit(data$PDS1))
missing$percna_PDS1 <- (missing$na_PDS1/length(data$PDS1))*100
missing$na_PDS2 <- length(data$PDS2)-length(na.omit(data$PDS2))
missing$percna_PDS2 <- (missing$na_PDS2/length(data$PDS2))*100
missing$na_PDS3 <- length(data$PDS3)-length(na.omit(data$PDS3))
missing$percna_PDS3 <- (missing$na_PDS3/length(data$PDS3))*100
missing$na_PDS4 <- length(data$PDS4)-length(na.omit(data$PDS4))
missing$percna_PDS4 <- (missing$na_PDS4/length(data$PDS4))*100
missing$na_PDS6 <- length(data$PDS6)-length(na.omit(data$PDS6))
missing$percna_PDS6 <- (missing$na_PDS6/length(data$PDS6))*100
missing$na_PBIP1 <- length(data$PBIP1)-length(na.omit(data$PBIP1))
missing$percna_PBIP1 <- (missing$na_PBIP1/length(data$PBIP1))*100
missing$na_PBIP2 <- length(data$PBIP2)-length(na.omit(data$PBIP2))
missing$percna_PBIP2 <- (missing$na_PBIP2/length(data$PBIP2))*100

# Specifying PDS & PBIP variables as ordinal
data_ord <- data
data_menarche <- data
data_mpbip <- data
data_ord[, 17:23] <- lapply(data_ord[, 17:23], ordered)
data_menarche$PDS6 <- ordered(data_menarche$PDS6)
data_mpbip[, 21:23] <- lapply(data_mpbip[, 21:23], ordered)
```

## PART 1: SELF-REPORT MODELS ONLY 
```{r SRMs}

# Define SRM1 - Self-Report Only with 1 Puberty Factor. No covariances
sr1 <- "
#Latent Neuroendocrine Systems
puberty =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2
"
# Define SRM3 - Self-Report Only with 1 Puberty Factor. WITH covariances. No covar on PDS6 bc it's binary
sr3 <- "
#Latent Neuroendocrine Systems
puberty =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#Covariances for questionnaires
PDS1 ~~ PDS2 + PDS3 + PDS4
PDS2 ~~ PDS3 + PDS4
PDS3 ~~ PDS4
PBIP1 ~~ PBIP2
"

#Because PDS1 has the worst loading, make models without that indicator
sr1_noPDS1 <- "
#Latent Neuroendocrine Systems
puberty =~ PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2
"

sr3_noPDS1 <- "
#Latent Neuroendocrine Systems
puberty =~ PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#Covariances for questionnaires
PDS2 ~~ PDS3 + PDS4
PDS3 ~~ PDS4
PBIP1 ~~ PBIP2
"

# Define SRM2 - Self-Report Only with 2 Puberty Factors (Adrenal & Gonadal). No covariances.
sr2 <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS1 + PDS4 + PDS6 + PBIP1
"

# Define SRM4 - Self-Report Only with 2 Puberty Factors (Adrenal & Gonadal). WITH covariances.
sr4 <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS1 + PDS4 + PDS6 + PBIP1

#Covariances for questionnaires (minus pds6)
PDS1 ~~ PDS2 + PDS3 + PDS4
PDS2 ~~ PDS3 + PDS4
PDS3 ~~ PDS4
PBIP1 ~~ PBIP2
"

#2 factors SRMs without PDS1 again
sr2_noPDS1 <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS4 + PDS6 + PBIP1
"

sr4_noPDS1 <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS4 + PDS6 + PBIP1

#Covariances for questionnaires
PDS2 ~~ PDS3 + PDS4
PDS3 ~~ PDS4
PBIP1 ~~ PBIP2
"

# ** Fit Self-Report CFAs (ordinal data) - PML - USE THIS **
fit_sr1_pml <- cfa(sr1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr2_pml <- cfa(sr2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr3_pml <- cfa(sr3, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr4_pml <- cfa(sr4, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# No PDS1
fit_sr1_noPDS1_pml <- cfa(sr1_noPDS1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr2_noPDS1_pml <- cfa(sr2_noPDS1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr3_noPDS1_pml <- cfa(sr3_noPDS1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr4_noPDS1_pml <- cfa(sr4, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Model Stats & Comparison 

#Do we need covariances between items of the same questionnaire?
anova(fit_sr3_pml, fit_sr1_pml) # 1 factor models
anova(fit_sr4_pml, fit_sr2_pml) # 2 factor models
#For all models, adding covariances for self-report Qs does not increase model fit indices.


#Is self-reported puberty better captured by A+G or P? 

# One vs 2 factor for models - NO covariances
summary(fit_sr1_pml, fit.measures = T, standardized = T)
summary(fit_sr2_pml, fit.measures = T, standardized = T)

lavTestLRT(fit_sr1_pml, fit_sr2_pml)

fitmea_sr1_pml <- fitmeasures(fit_sr1_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
fitmea_sr2_pml <- fitmeasures(fit_sr2_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
#AG fits better than P for model with NO covariances between items of the same questionnaire
#data treated as ordinal, and pml estimator (p=0.09)

# One vs 2 factor for models - WITH covariances
summary(fit_sr3_pml, fit.measures = T, standardized = T)
summary(fit_sr4_pml, fit.measures = T, standardized = T)

lavTestLRT(fit_sr3_pml, fit_sr4_pml)

fitmea_sr3_pml <- fitmeasures(fit_sr3_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
fitmea_sr4_pml <- fitmeasures(fit_sr4_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))


# Check 1 vs 2 factor when PDS1 is not included
summary(fit_sr1_noPDS1_pml, fit.measures = T, standardized = T)
summary(fit_sr2_noPDS1_pml, fit.measures = T, standardized = T)
lavTestLRT(fit_sr1_noPDS1_pml, fit_sr2_noPDS1_pml)

fitmea_sr1_noPDS1_pml <- fitmeasures(fit_sr1_noPDS1_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
fitmea_sr2_noPDS1_pml <- fitmeasures(fit_sr2_noPDS1_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

# There is no significant difference between a 1 and 2 factor model even when PDS1 is not included. Model fit indices are also not better when PDS1 is removed, so PDS1 remains in the models from now on.

# Finally, also check if using MLR changes much from PML (for possible use in Full Models later)
#fit_sr1_mlr <- cfa(sr1, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

#fit_sr2_mlr <- cfa(sr2, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

#fit_sr3_mlr <- cfa(sr3, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

#fit_sr4_mlr <- cfa(sr4, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

#summary(fit_sr1_mlr, fit.measures = T, standardized = T)
#fitmea_sr1_mlr <- fitmeasures(fit_sr1_mlr,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea",
#                             "srmr"))
#summary(fit_sr2_mlr, fit.measures = T, standardized = T)
#fitmea_sr2_mlr <- fitmeasures(fit_sr2_mlr,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea",
#                             "srmr"))
#summary(fit_sr3_mlr, fit.measures = T, standardized = T)
#fitmea_sr3_mlr <- fitmeasures(fit_sr3_mlr,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea",
#                             "srmr"))
#summary(fit_sr4_mlr, fit.measures = T, standardized = T)
#fitmea_sr4_mlr <- fitmeasures(fit_sr4_mlr,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea",
#                             "srmr"))

```


## Step 2: Hormone Models - Saliva + Hair. All have no equality constraints. 
```{r HMs}
##########

# First we run all four models WITH BOTH latent hormone (DHEA, T, E2) and neuroendocrine (ADR, GON, PUB) factors. Even though the one- and two-factor models are equivalent

##########

# Define HM1 - one factor, no covariances, hair + saliva
hm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
puberty =~ dhea + estr + test

"

# Fit HM1 - can only get MLR to converge (? check this):

fit_hm1 <- cfa(hm1, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") #even with MLR, some estimated lv variances are negative

fit_hm1_pml <- cfa(hm1, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr") #the optimizer warns that a solution has NOT been found!

# Summary Stats for HM1
summary(fit_hm1_pml, fit.measures = T, standardized = T)
# below doesn't work bc didn't converge
# fitmea_hm1_pml <- fitMeasures(fit_hm1_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

# Pictoral Representation of HM1
#semPaths(fit_hm1)


# Define HM2 - two factors, no covariances, hair + saliva
hm2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
adrenal =~ dhea + test

"

# Fit HM2 - can only get PML to converge:

#fit_hm2 <- cfa(hm2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") #the optimizer warns that a solution has NOT been found!

fit_hm2_pml <- cfa(hm2, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr") # some dodgy stuff still happens but you can still get some estimates

# Summary Stats for HM2
summary(fit_hm2_pml, fit.measures = T, standardized = T)
fitmea_hm2_pml <- fitMeasures(fit_hm2_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

# Pictoral Representation of HM2
semPaths(fit_hm2_pml)

# Define HM3 - one factor, WITH covariances, hair + saliva
hm3 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
puberty =~ dhea + estr + test

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM3
# fit_hm3 <- cfa(hm3, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr")
fit_hm3_pml <- cfa(hm3, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HM3
# summary(fit_hm3, fit.measures = T, standardized = T)
# fitMeasures(fit_hm3, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

summary(fit_hm3_pml, fit.measures = T, standardized = T)
fitmea_hm3_pml <- fitMeasures(fit_hm3_pml,
                              fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue","rmsea"))

# Pictoral Representation of HM3
semPaths(fit_hm3_pml)

# Define HM4 - two factors, WITH covariances, hair + saliva 
hm4 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
adrenal =~ dhea + test

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM4 - only PML converges:

#fit_hm4 <- cfa(hm4, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") #the optimizer warns that a solution has NOT been found! 
fit_hm4_pml <- cfa(hm4, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for HM4
#summary(fit_hm4, fit.measures = T, standardized = T)
#fitMeasures(fit_hm4, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm4_pml, fit.measures = T, standardized = T)
fitmea_hm4_pml <- fitMeasures(fit_hm4_pml, 
                              fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

# Pictoral Representation of HM4
semPaths(fit_hm4_pml)

#lavTestLRT(fit_hm1_pml, fit_hm3_pml)
lavTestLRT(fit_hm2_pml, fit_hm4_pml)

#lavTestLRT(fit_hm1_pml, fit_hm2_pml)
#lavTestLRT(fit_hm3_pml, fit_hm4_pml)

##########

# Second, because no HMs above worked whatsoever, we run all four models without the latent hormone (DHEA, T, E2) variables and everything loads directly onto neuroendocrine (ADR, GON, PUB) factors. These are HMv2 (hormone models version 2). Currently this is what's reported in the manuscript. I've run these both with PML and MLR estimators below but MLR is more appropriate because all the hormone models have continuous indicators, and this is what we reported in the final version.

##########

# Define HM1v2 - one factor, no covariances, hair + saliva
hm1v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + 0*dhea_hair + estr_hair + test_hair

"

# Fit HM1v2:
fit_hm1v2_pml <- cfa(hm1v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 
fit_hm1v2_mlr <- cfa(hm1v2, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for HM1v2

summary(fit_hm1v2_pml, fit.measures = T, standardized = T)
fitmea_hm1v2_pml <- fitMeasures(fit_hm1v2_pml,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))

summary(fit_hm1v2_mlr, fit.measures = T, standardized = T)
fitmea_hm1v2_mlr <- fitMeasures(fit_hm1v2_mlr,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HM1
# semPaths(fit_hm1v2)
semPaths(fit_hm1v2_pml)

# Define HM2v2 - two factors, no covariances, hair + saliva
hm2v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test + 0*dhea_hair + test_hair
gonadal =~ sal_estr + estr_hair
"

# Fit HM2v2:

fit_hm2v2_pml <- cfa(hm2v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

fit_hm2v2_mlr <- cfa(hm2v2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for HM2v2
# summary(fit_hm2v2, fit.measures = T, standardized = T)
# fitMeasures(fit_hm2v2, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm2v2_pml, fit.measures = T, standardized = T)
fitmea_hm2v2_pml <- fitMeasures(fit_hm2v2_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))
summary(fit_hm2v2_mlr, fit.measures = T, standardized = T)
fitmea_hm2v2_mlr <- fitMeasures(fit_hm2v2_mlr, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of HM2v2
#semPaths(fit_hm2v2)
semPaths(fit_hm2v2_pml)
semPaths(fit_hm2v2_mlr)

# Define HM3v2 - one factor, WITH covariances, hair + saliva
hm3v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + 0*dhea_hair + estr_hair + test_hair

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM3v2

fit_hm3v2_pml <- cfa(hm3v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

fit_hm3v2_mlr <- cfa(hm3v2, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

# Summary Stats for HM3

summary(fit_hm3v2_pml, fit.measures = T, standardized = T)
fitmea_hm3v2_pml <- fitMeasures(fit_hm3v2_pml,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))

summary(fit_hm3v2_mlr, fit.measures = T, standardized = T)
fitmea_hm3v2_mlr <- fitMeasures(fit_hm3v2_mlr,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HM3v2
# semPaths(fit_hm3v2)
semPaths(fit_hm3v2_pml)

# Define HM4v2 - two factors, WITH covariances, hair + saliva 
hm4v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test + 0*dhea_hair + test_hair
gonadal =~ sal_estr + estr_hair

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM4v2:
fit_hm4v2_pml <- cfa(hm4v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

fit_hm4v2_mlr <- cfa(hm4v2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for HM4v2
summary(fit_hm4v2_pml, fit.measures = T, standardized = T)
fitmea_hm4v2_pml <- fitMeasures(fit_hm4v2_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))
summary(fit_hm4v2_mlr, fit.measures = T, standardized = T)
fitmea_hm4v2_mlr <- fitMeasures(fit_hm4v2_mlr, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of HM4
# semPaths(fit_hm4v2)
semPaths(fit_hm4v2_pml)

#Compare models
lavTestLRT(fit_hm1v2_pml, fit_hm3v2_pml) # 1 factor with or w/o covar? p=0.07913
lavTestLRT(fit_hm2v2_pml, fit_hm4v2_pml) # 2 factor with or w/o covar? p=0.3381

lavTestLRT(fit_hm1v2_pml, fit_hm2v2_pml) # 1 or 2 factor w/o covar? p=0.3786
lavTestLRT(fit_hm3v2_pml, fit_hm4v2_pml) # 1 or 2 factor with covar? p=0.3625

# MLR estimator (more appropriate for continuous data)
lavTestLRT(fit_hm1v2_mlr, fit_hm3v2_mlr) # 1 factor with or w/o covar? 
lavTestLRT(fit_hm2v2_mlr, fit_hm4v2_mlr) # 2 factor with or w/o covar? 

lavTestLRT(fit_hm1v2_mlr, fit_hm2v2_mlr) # 1 or 2 factor w/o covar? 
lavTestLRT(fit_hm3v2_mlr, fit_hm4v2_mlr) # 1 or 2 factor with covar? 

```

## Step 3: Post hoc Hormone Models 1 (Reduced hormone models) - Hair E2 ONLY + Saliva (no hair DHEA or hair T)
```{r RHMs}

# Define RHM1 - one factor, no covariances, hair E2 only + saliva
rhm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + estr_hair 

"

# Fit RHM1:
fit_rhm1_pml <- cfa(rhm1, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 
fit_rhm1_mlr <- cfa(rhm1, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for RHM1
summary(fit_rhm1_pml, fit.measures = T, standardized = T)
fitmea_rhm1_pml <- fitMeasures(fit_rhm1_pml,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))

summary(fit_rhm1_mlr, fit.measures = T, standardized = T)
fitmea_rhm1_mlr <- fitMeasures(fit_rhm1_mlr,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HM1
semPaths(fit_rhm1_pml)

# Define RHM2 - two factors, no covariances, hair E2 only + saliva
rhm2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test 
gonadal =~ sal_estr + estr_hair
"

# Fit RHM2:
fit_rhm2_pml <- cfa(rhm2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 
fit_rhm2_mlr <- cfa(rhm2, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for RHM2
summary(fit_rhm2_pml, fit.measures = T, standardized = T)
fitmea_rhm2_pml <- fitMeasures(fit_rhm2_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))
summary(fit_rhm2_mlr, fit.measures = T, standardized = T)
fitmea_rhm2_mlr <- fitMeasures(fit_rhm2_mlr, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of RHM2
semPaths(fit_rhm2_pml)

# Define RHM3 - one factor, WITH covariances, hair E2 only + saliva
rhm3 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + estr_hair

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit RHM3
fit_rhm3_pml <- cfa(rhm3, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")
fit_rhm3_mlr <- cfa(rhm3, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

# Summary Stats for RHM3
summary(fit_rhm3_pml, fit.measures = T, standardized = T)
fitmea_rhm3_pml <- fitMeasures(fit_rhm3_pml,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))
summary(fit_rhm3_mlr, fit.measures = T, standardized = T)
fitmea_rhm3_mlr <- fitMeasures(fit_rhm3_mlr,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))
# Pictoral Representation of RHM3
semPaths(fit_rhm3_pml)

# Define RHM3 - two factors, WITH covariances, hair E2 only + saliva 
rhm4 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test 
gonadal =~ sal_estr + estr_hair

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit RHM4:
fit_rhm4_pml <- cfa(rhm4, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 
fit_rhm4_mlr <- cfa(rhm4, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for RHM4
summary(fit_rhm4_pml, fit.measures = T, standardized = T)
fitmea_rhm4_pml <- fitMeasures(fit_rhm4_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))
summary(fit_rhm4_mlr, fit.measures = T, standardized = T)
fitmea_rhm4_mlr <- fitMeasures(fit_rhm4_mlr, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))
# Pictoral Representation of RHM4
semPaths(fit_rhm4_pml)

#Compare models
lavTestLRT(fit_rhm1_pml, fit_rhm3_pml) # 1 factor with or w/o covar? 
lavTestLRT(fit_rhm2_pml, fit_rhm4_pml) # 2 factor with or w/o covar? 

lavTestLRT(fit_rhm1_pml, fit_rhm2_pml) # 1 or 2 factor w/o covar? 
lavTestLRT(fit_rhm3_pml, fit_rhm4_pml) # 1 or 2 factor with covar? 

lavTestLRT(fit_rhm1_mlr, fit_rhm3_mlr) # 1 factor with or w/o covar? 
lavTestLRT(fit_rhm2_mlr, fit_rhm4_mlr) # 2 factor with or w/o covar? 

lavTestLRT(fit_rhm1_mlr, fit_rhm2_mlr) # 1 or 2 factor w/o covar? 
lavTestLRT(fit_rhm3_mlr, fit_rhm4_mlr) # 1 or 2 factor with covar? 


# SALIVA ONLY MODELS (ONE-FACTOR ONLY) - put in supplemental:
slm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test

"

# Fit SLM1:
fit_slm1_mlr <- cfa(slm1, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr") 

# Summary Stats for SLM1
summary(fit_slm1_mlr, fit.measures = T, standardized = T)
fitmea_slm1_mlr <- fitMeasures(fit_slm1_mlr,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))


# Define SLM3 - one factor, WITH covariances, saliva
slm3 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit SLM3
fit_slm3_mlr <- cfa(slm3, data = data, missing = "ML", estimator = "MLR", se = "robust.mlr")

# Summary Stats for SLM3
summary(fit_slm3_mlr, fit.measures = T, standardized = T)
fitmea_slm3_mlr <- fitMeasures(fit_slm3_mlr,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))
lavTestLRT(fit_slm1_mlr, fit_slm3_mlr) # 1 factor with or w/o covar? 

```


## Step 4 - Post hoc hormone Models 2 - Hair Predicts Saliva
```{r Hair Predicts Saliva}
# Define HSM1 - No methods factors
hsm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Regressions
sal_dhea ~ dhea_hair
sal_estr ~ estr_hair
sal_test ~ test_hair

#Covariances for Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4
"
# Define HSM2 (hair saliva model with method factors)
hsm2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Regressions
sal_dhea ~ dhea_hair
sal_estr ~ estr_hair
sal_test ~ test_hair

#Covariances for Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Methods Factors
hair =~ dhea_hair + estr_hair + test_hair
saliva =~ dhea1 + dhea2 + dhea3 + dhea4 + estr1 + estr2 + estr3 + estr4 + test1 + test2 + test3 + test4

#Set Latent Var Covariances to Zero
hair ~~ 0*saliva + 0*sal_dhea + 0*sal_estr + 0*sal_test
saliva ~~ 0*sal_dhea + 0*sal_estr + 0*sal_test
"

# Fit HSM1 All Data
fit_hsm1_pml <- cfa(hsm1, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HSM1
summary(fit_hsm1_pml, fit.measures = T, standardized = T) 
fitmea_hsm1_pml <- fitMeasures(fit_hsm1_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

semPaths(fit_hsm1_pml)

# Fit Model HSM2
fit_hsm2_pml <- cfa(hsm2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HSM2
summary(fit_hsm2_pml, fit.measures = T, standardized = T) 
fitmea_hsm2_pml <- fitMeasures(fit_hsm2_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HSMs
semPaths(fit_hsm1_pml)
semPaths(fit_hsm2_pml)

# Comparing Model Fits - wait these don't work
lavTestLRT(fit_hsm1_pml, fit_hsm2_pml)

```

Step 5: dracarys
```{r FMs}
##########
# All models here are "version 2 or 3" (version 1 was including all hair indicators, which we don't want to do according to HM results). 

# Versions 2 have hair E2 (only) in them, versions 3 are saliva only (no hair). We also tried with and without covariances for the saliva days. We ran them all first using PML and got warnings, although lavaan gave us estimates and loadings anyway. "optim.gradients" were all zero and the fit indices were fine, so we have presented the PML results for all full models.

##########

# Define Full Model (FM)1v2 - one factor, including hair E2 only and all saliva, second level factors for self-report only:

fm1v2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test + estr_hair

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit FM1v2 - using PML 
fit_fm1v2_pml <- cfa(fm1v2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
# may not found local solution, try playing around with the iterations or other control options (note I tried this and it still stops at 288 iterations and "not all elements of the gradient are (near) zero), but using lavInspect and "optim.gradient" they are all at zero! The fit for these seem fine so we presented the PML findings:
#fit_fm1v2_pml <- cfa(fm1v2, data = data, estimator = "PML", 
#                     missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6","PBIP1","PBIP2"), 
#                     control = list(iter.max=1000)) #Note this only does #max, can't seem to figure out how to make it do more iterations and not give #up

# Fit FM1v2 - using MLR (decided not to present this becuase even though getting warnings with PML the fit and gradients seem fine...)
# fit_fm1v2_mlr <- cfa(fm1v2, data = data, missing = "ML", estimator = "MLR",
#                     se = "robust.mlr")

# Summary Stats for Full Model 1 v2
summary(fit_fm1v2_pml, fit.measures = T, standardized = T) 
fitmea_fm1v2_pml <- fitmeasures(fit_fm1v2_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea",
                             "srmr")) 

# Pictoral Representation of Full Model 1 v2
semPaths(fit_fm1v2_pml)

#Just check it's not better without saliva days covarying
fm1v2_nocov <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test + estr_hair

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

"

# Fit FM1v2 no covariates - using PML 
fit_fm1v2_pml_nocov <- cfa(fm1v2_nocov, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))


# Summary Stats for Full Model 1 v2 no covariates
summary(fit_fm1v2_pml_nocov, fit.measures = T, standardized = T) 
fitmea_fm1v2_pml_nocov <- fitmeasures(fit_fm1v2_pml_nocov,
            fit.measures = c("cfi","ecvi","mfi")) 


# Define Full Model (FM)2v2 - two factor, including hair E2, second level factors (hormone and self-report)
fm2v2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + estr_hair + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit FM2v2

fit_fm2v2_pml <- cfa(fm2v2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for FM2v2
summary(fit_fm2v2_pml, fit.measures = T, standardized = T)
fitmea_fm2v2_pml <- fitmeasures(fit_fm2v2_pml, fit.measures = c("cfi","ecvi","mfi"))

fit_fm2v2_pml_parest <- parameterEstimates(fit_fm2v2_pml)
lavaan:::ctr_pml_plrt(fit_fm2v2_pml)

# Pictoral Representation of FM2v2
semPaths(fit_fm2v2_pml)

#Compare two- and one-factor models that include E2 hair only and all saliva
anova(fit_fm2v2_pml, fit_fm1v2_pml) 
lrtest(fit_fm2v2_pml, fit_fm1v2_pml)

####
## But also check what happens when you constrain SR_GON and Sal_E2 (because these loadings for GON are fairly similar) or constrain SR_ADR and Sal_DHEA (where loadings are not so similar between SR and spit, so maybe for ADR especially, you need both):
fm2v2_goncon <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + estr_hair + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

# constrain SR and saliva for GON to see if it's ok
gonadal ~~ c*sal_estr
gonadal ~~ c*gonadal_sr
"

fm2v2_adrcon <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + estr_hair + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

# constrain SR and saliva (just chose DHEA but could do T instead) for ADR to see if it's ok (probs not, so then you really need SR and spit)
adrenal ~~ c*sal_test
gonadal ~~ c*adrenal_sr
"
fit_fm2v2_goncon <- cfa(fm2v2_goncon, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
fit_fm2v2_adrcon <- cfa(fm2v2_adrcon, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
summary(fit_fm2v2_goncon, fit.measures = T, standardized = T)
fitmea_fm2v2_goncon <- fitmeasures(fit_fm2v2_goncon, fit.measures = c("cfi","ecvi","mfi"))
summary(fit_fm2v2_adrcon, fit.measures = T, standardized = T)
fitmea_fm2v2_adrcon <- fitmeasures(fit_fm2v2_adrcon, fit.measures = c("cfi","ecvi","mfi"))
anova(fit_fm2v2_goncon, fit_fm2v2_pml)
anova(fit_fm2v2_adrcon, fit_fm2v2_pml)
lavInspect(fit_fm2v2_goncon, what = "post.check")
lavInspect(fit_fm2v2_adrcon, what = "post.check")



######
#Extracting latent variable estimates per subject for funsies

# lve1.puberty is 1 factor score from full model with saliva and hair E2
fit_fm1v2_extract_vars <- lavPredict(fit_fm1v2_pml, method = "EBM", type = "lv")
fm1v2_lve <- as.data.frame(fit_fm1v2_extract_vars)
pub_lve <- select(fm1v2_lve, "puberty")
data$lve1 <- pub_lve

# lve2.adrenal and lve3.gonadal are the 2 factor scores from full model with saliva and hair E2
fit_fm2v2_extract_vars <- lavPredict(fit_fm2v2_pml, method = "EBM", type = "lv")
fm2v2_lve <- as.data.frame(fit_fm2v2_extract_vars)
adr_lve <- select(fm2v2_lve, "adrenal")
gon_lve <- select(fm2v2_lve, "gonadal")
data$lve2 <- adr_lve
data$lve3 <- gon_lve

write.csv(data, "Z:/dsnlab/TAG/projects/W1_puberty_modelling/data_lve.csv")


#####
# Versions 3 - Try full models again with ONLY saliva (not even E2 hair)
fm1v3 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit FM1v3 - using PML 
fit_fm1v3_pml <- cfa(fm1v3, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))


# Summary Stats for Full Model 1 v3
summary(fit_fm1v3_pml, fit.measures = T, standardized = T) 
fitmea_fm1v3_pml <- fitmeasures(fit_fm1v3_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr")) 

# Pictoral Representation of Full Model 1 v3
semPaths(fit_fm1v3_pml)

#fm1 v3 with NO covariances
fm1v3_nocov <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

"

# Fit FM1v3 no cov - using PML 
fit_fm1v3_pml_nocov <- cfa(fm1v3_nocov, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))


# Summary Stats for Full Model 1 v3
summary(fit_fm1v3_pml_nocov, fit.measures = T, standardized = T) 
fitmea_fm1v3_pml_nocov <- fitmeasures(fit_fm1v3_pml_nocov,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr")) 


# Define Full Model (FM)2v3 - two factor, including hair, second level factors (hormone and self-report)
fm2v3 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit FM2v3

fit_fm2v3_pml <- cfa(fm2v3, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for FM2v3
summary(fit_fm2v3_pml, fit.measures = T, standardized = T)
fitmea_fm2v3_pml <- fitmeasures(fit_fm2v3_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

fit_fm2v3_pml_parest <- parameterEstimates(fit_fm2v3_pml)
lavaan:::ctr_pml_plrt(fit_fm2v3_pml)

# Pictoral Representation of FM2v3
semPaths(fit_fm2v3_pml)

#Compare two- and one-factor models that include only saliva
anova(fit_fm2v3_pml, fit_fm1v3_pml) 
lrtest(fit_fm2v3_pml, fit_fm1v3_pml)


```

```{r age_analyses}
########## AGE POSTHOC ANALYSES ##########
# Try FM2v2 (2 factor, hair E2) but:
# 1) correlate both ADR and GON with age (FM2v2_agecor)
# 2) correlate ADR and GON controlling for age (FM2v2_ageres)
# Check the age correlation for the one-factor model, too (FM1v2_agecor), and the self-report models

# first add age back to the dataset
age <- read.csv(file.path(workdir,"Demographics/Age/TAG_age.csv", fsep=""))
agew1s1 <- age[ which(age$wave=='1' & age$session=='1'), ]
agevars <- c("SID", "age")
agew1s1 <- agew1s1[agevars]
data_age <- inner_join(agew1s1, data, by = "SID")

#now build the first one, ADR and GON correlate with age (note that lavaan automatically shows correlations for ADR and GON and Agefac)
fm2v2_agecor <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + estr_hair + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#covary observed age and latent neuroendo systems by tricking lavaan (remember that lavaan always fixes the first loading to 1)
agefac =~ age
"
#now build the second one, ADR and GON correlate, controlling for age 
fm2v2_ageres <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + estr_hair + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

# tricking lavaan again
agefac =~ age

#factor regressions on age
adrenal ~ agefac
gonadal ~ agefac
"
# Finally, see if agecor fit is worse if you constrain age correlations to be the same across ADR and GON (because then age is more correlated with one, in this case GON 0.695 vs ADR 0.580)
fm2v2_agecorcon <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ sal_dhea + sal_test + adrenal_sr
gonadal =~ sal_estr + estr_hair + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#covary observed age and latent neuroendo systems 
agefac =~ age

# constrain correlations to see if it fits worse than fm2v2_agecor
adrenal ~~ c*agefac
gonadal ~~ c*agefac
"

# Check the age correlation with the one factor PUB latent variable, too
fm1v2_agecor <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test + estr_hair

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#age factor
agefac =~ age
"
# Do the same for self-report models only
sr1_agecor <- "
#Latent Neuroendocrine Systems
puberty =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#age factor
agefac =~ age
"

sr2_agecor <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS1 + PDS4 + PDS6 + PBIP1

#age factor
agefac =~ age
"

# Fit fm2v2_agecor, fm2v2_ageres, and fm2v2_agecorcon
fit_fm2v2_agecor <- cfa(fm2v2_agecor, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
fit_fm2v2_ageres <- cfa(fm2v2_ageres, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
fit_fm2v2_agecorcon <- cfa(fm2v2_agecorcon, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
fit_fm1v2_agecor <- cfa(fm1v2_agecor, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr1_agecor <- cfa(sr1_agecor, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))
fit_sr2_agecor <- cfa(sr2_agecor, data = data_age, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for FM2v2_agecor, FM2v2_ageres, and fm2v2_agecorcon
summary(fit_fm2v2_agecor, fit.measures = T, standardized = T)
fitmea_fm2v2_agecor <- fitmeasures(fit_fm2v2_agecor, fit.measures = c("cfi","ecvi","mfi"))

summary(fit_fm2v2_ageres, fit.measures = T, standardized = T)
fitmea_fm2v2_ageres <- fitmeasures(fit_fm2v2_ageres, fit.measures = c("cfi","ecvi","mfi"))

summary(fit_fm2v2_agecorcon, fit.measures = T, standardized = T)
fitmea_fm2v2_agecorcon <- fitmeasures(fit_fm2v2_agecorcon, fit.measures = c("cfi","ecvi","mfi"))

summary(fit_fm1v2_agecor, fit.measures = T, standardized = T)
fitmea_fm1v2_agecor <- fitmeasures(fit_fm1v2_agecor, fit.measures = c("cfi","ecvi","mfi"))

summary(fit_sr1_agecor, fit.measures = T, standardized = T)
fitmea_sr1_agecor <- fitmeasures(fit_sr1_agecor, fit.measures = c("cfi","ecvi","mfi"))

summary(fit_sr2_agecor, fit.measures = T, standardized = T)
fitmea_sr2_agecor <- fitmeasures(fit_sr2_agecor, fit.measures = c("cfi","ecvi","mfi"))

fit_fm2v2_agecor_parest <- parameterEstimates(fit_fm2v2_agecor)
lavaan:::ctr_pml_plrt(fit_fm2v2_agecor)

fit_fm2v2_ageres_parest <- parameterEstimates(fit_fm2v2_ageres)
lavaan:::ctr_pml_plrt(fit_fm2v2_ageres)

fit_fm2v2_agecorcon_parest <- parameterEstimates(fit_fm2v2_agecorcon)
lavaan:::ctr_pml_plrt(fit_fm2v2_agecorcon)

# see if agecorcon fits significantly worse than agecor (if so, age is more strongly correlated with GON than ADR)
anova(fit_fm2v2_agecor, fit_fm2v2_agecorcon)
lrtest(fit_fm2v2_agecor, fit_fm2v2_agecorcon)
# Turns out you can't do this because the agecorcon model was not positive-definite:
lavInspect(fit_fm2v2_agecor, what = "post.check")
lavInspect(fit_fm2v2_ageres, what = "post.check")
lavInspect(fit_fm2v2_agecorcon, what = "post.check")

# Pictoral Representation of FM2v2_agecor, FM2v2_ageres, and FM2v2_agecorcon
semPaths(fit_fm2v2_agecor)
semPaths(fit_fm2v2_ageres)
semPaths(fit_fm2v2_agecorcon)

## Compare correlations between age and the latent variables in the above models, with correlations with age using traditional self-report scales (PDS, LDs), or with mean value of salivary hormones.
pub_scores <- read.csv(file.path(workdir,"../Projects/W1_W2_pubertal_timing/Timing_allways_w1.csv", fsep="")) #note: these are the same subjects that are in "data" but ok to keep separate because we aren't doing correlations across the observed scores (pub_scores) and the latent variables (data)
pubvars <- c("pdsstage", "pdsscore", "age", "PUBcomp", "ADRENcomp", "GONADcomp", "mean_DHEA_ln", "mean_TEST_ln", "mean_EST_ln")
pub_scores <- pub_scores[pubvars]
allhorm <- c("mean_DHEA_ln", "mean_TEST_ln", "mean_EST_ln")
pub_scores$mean_allhorm <- rowMeans(pub_scores[allhorm])
adrhorm <- c("mean_DHEA_ln", "mean_TEST_ln")
pub_scores$mean_adrhorm <- rowMeans(pub_scores[adrhorm])
library(Hmisc)
library(corrplot)
pub_corr <- rcorr(as.matrix(pub_scores))
pub_corr$r
pub_corr$P

# PUB composite (PDS/LD) & age: r = 0.4964629
# All saliva (mean DHEA, T, E2) & age: r = 0.5302742
#     Compare this to the latent PUB (FM1_v2_agecor) and Age correlation, r = 0.724
#       Or even the latent PUB Self-report and Age correlation, r = 0.522

# ADREN composite (PDS/LD) & age: r = 0.4940295
# ADR Saliva (mean DHEA, T) & age: r = 0.4968588
#     Compare this to the latent ADR (FM2_v2_agecor) and Age correlation: r = 0.580
#       Compare to latent ADR Self-report and Age correlation, r = 0.527

# GONAD composite (PDS/LD) & age: r = 0.4057057
# GON Saliva (mean E2) & age: r = 0.4496975
#     Compare this to the latent GON (FM2_v2_agecor) and Age correlation, r = 0.695
#       Compare to latent GON Self-report and Age correlation, r = 0.483

# Further comparisons to consider calculating:
#   Composite (PUBcomp) + saliva (mean DHEA, T, E2) & age
#   ADREN Composite + saliva (mean DHEA, T) & age
#   GONAD Composite + saliva (mean E2) & age
#   Compared to CFA SR + saliva (FM2) & age

```


```{r}

h_sr_cov <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test + estr_hair


#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

fit_h_sr_cov_pml <- cfa(h_sr_cov, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for h_sr_cov
summary(fit_h_sr_cov_pml, fit.measures = T, standardized = T)
fitmea_h_sr_cov_pml <- fitmeasures(fit_h_sr_cov_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

semPaths(fit_h_sr_cov_pml)

#Extracting Latent Variable Estimates per Subject
h_sr_cov_extract_vars <- lavPredict(fit_h_sr_cov_pml, method = "EBM", type = "lv") 

#Correlation Matrices for Latent Var Estimates
h_sr_cov_cor <- cor(h_sr_cov_extract_vars)
fm1v2_p_bio_sr_r2 <- (sem1_cor[5,4])*(sem1_cor[5,4])


# "P" bio with hair predict "P" self-report
# NOTE: you're not supposed to do this so we didn't include it
sem1_p_plot <- plot(sem1_extract_vars[,"sr_puberty"] ~ sem1_extract_vars[,"bio_puberty"], ylab = "Estimates for Self-Reported Puberty", xlab = "Estimates for Hormone Puberty") + title(main = "Extracted Latent Variables:\n One-factor Puberty") + abline(lm(sem1_extract_vars[,"sr_puberty"] ~ sem1_extract_vars[,"bio_puberty"])) + 
  text(x=1.4, y=-1.2, labels = bquote(italic(R)^2 == .(format(sem1_p_bio_sr_r2))))


```


```{r save and export}
# Fit measures
fitmea_sr <- data.frame(fitmea_sr1_pml, fitmea_sr2_pml, fitmea_sr3_pml,
                         fitmea_sr4_pml)
fitmea_rhm <- data.frame(fitmea_rhm1_mlr, fitmea_rhm2_mlr, fitmea_rhm3_mlr,
                         fitmea_rhm4_mlr)
fitmea_hsm <- data.frame(fitmea_hsm1_pml, fitmea_hsm2_pml)
fitmea_fm <- data.frame(fitmea_fm1v2_pml, fitmea_fm2v2_pml)

# Save environment
save.image("Z:/dsnlab/TAG/projects/W1_puberty_modelling/Puberty_CFA_v2.RData")

```

