---
title: "puberty_cca"
author: "Theresa Cheng"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages = c("tidyr", "dplyr", "rio", "stringr")

# load packages, install as needed
package.check <- lapply(packages, FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
        install.packages(x, dependencies = TRUE)
        library(x, character.only = TRUE) }})
```

```{r load data}

save_clean_data = FALSE

# data files
data_dir <- "/Volumes/psych-cog/dsnlab/TAG/behavior"
output_dir <- "/Volumes/psych-cog/dsnlab/TAG/projects/W1_puberty_cca"
saliva_file <- "/Puberty/Saliva/Wave1/TAG_W1_Saliva_wide_cens_only4.csv"
hair_file <- "/Puberty/Hair/Wave1/TAG_W1_Hair_processed.csv"
pds_file <- "/Questionnaires/Wave1/PDS_Wave1.csv"
pbip_file <- "/Questionnaires/Wave1/PBIP_Wave1.csv"
ctq_file <- "/Questionnaires/Wave1/CTQ_Wave1.csv"
free_lunch_file <- "/Demographics/ParentQ_SES/TAG_W1_SES_ParentQ.xlsx"

#special
pss_file <- "/Volumes/psych-cog/dsnlab/TAG/projects/W1_puberty_cca/PSS_Wave1.RDS"

# load and clean saliva data
saliva_df <- import(paste0(data_dir, saliva_file))
saliva_df$SID <- str_pad(saliva_df$SID, 3, pad = "0")
saliva_df$SID <- paste0("TAG", saliva_df$SID)

# get age
age_df <- saliva_df[, c("SID", "ageS2")]

# ok continuing on with saliva now
saliva_df_EST <- saliva_df[, c("SID", "sal_EST_conc_ln_w_1", "sal_EST_conc_ln_w_2", "sal_EST_conc_ln_w_3", "sal_EST_conc_ln_w_4")]
saliva_df_TEST <- saliva_df[, c("SID", "sal_TEST_conc_ln_w_1", "sal_TEST_conc_ln_w_2", "sal_TEST_conc_ln_w_3", "sal_TEST_conc_ln_w_4")]
saliva_df_DHEA <- saliva_df[, c("SID", "sal_DHEA_conc_ln_w_1", "sal_DHEA_conc_ln_w_2", "sal_DHEA_conc_ln_w_3", "sal_DHEA_conc_ln_w_4")]

find_saliva_mean <- function(saliva_df_hormone, hormone_name){
  df <- gather(saliva_df_hormone, key = "week" , value = "concentration", -SID) %>% 
  group_by(SID) %>% 
  summarise(mean = mean(concentration, na.rm = TRUE))
  df$SID <- as.character(df$SID)
  colnames(df) <- c("SID", paste0("mean_saliva_", hormone_name))
  return(df)
}

mean_EST <- find_saliva_mean(saliva_df_EST, "EST")
mean_TEST <- find_saliva_mean(saliva_df_TEST, "TEST")
mean_DHEA <- find_saliva_mean(saliva_df_DHEA, "DHEA")
saliva_mean_df <- full_join(mean_EST, mean_TEST, by = "SID") %>%
  full_join(., mean_DHEA, by = "SID")

# load hair data
hair_df <- import(paste0(data_dir, hair_file))
hair_df <- spread(hair_df[, -3], hormone, concentration_ln)
hair_df$SID <- as.character(hair_df$SID)
hair_df$SID <- str_pad(hair_df$SID, 3, pad = "0")
hair_df$SID <- paste0("TAG", hair_df$SID)

# merge hair and saliva data
hormone_df <- full_join(saliva_mean_df, hair_df, by = "SID") %>% 
  full_join(., age_df, by = "SID")

# load physical maturation data
pds_df <- import(paste0(data_dir, pds_file))
pds_df <- pds_df[, c("tagid", "PDS_F1", "PDS_F2", "PDS_F3", "PDS_F4", "PDS_F6")] # did not include Q 5 re: timing
colnames(pds_df) <- c("SID", "pds1_height", "pds2_hair", "pds3_skin", "pds4_breasts", "pds6_period")

pbip_df <- import(paste0(data_dir, pbip_file))
pbip_df <- pbip_df[, c("tagid", "PBIP_1A", "PBIP_2A")]
colnames(pbip_df) <- c("SID", "pbip1_breasts", "pbip2_pubic_hair")

physical_mat_df <- full_join(pds_df, pbip_df, by = "SID")

# load ctq
ctq_df <- import(paste0(data_dir, ctq_file))
ctq_df <- ctq_df[order(ctq_df$tagid), ]# order by SID

ctq_items = list( # EA
                c("CTQ_3", #_calledstupid", 
                   "CTQ_8", #_neverbeenborn", 
                   "CTQ_14", #_familyinsulting",
                   "CTQ_18", #_familyhatedme",
                   "CTQ_25"), #_emotionallyabused"),
                 # PA
                 c("CTQ_17", #_beatenbadly",
                   "CTQ_9", #_hithard",
                   "CTQ_11", #_leftwithbruises",
                   "CTQ_12", #_punishedwithbelt",
                   "CTQ_15"), #_physicallyabused"),
                 # SA
                 c("CTQ_20", #_touchsexual",
                   "CTQ_21", #_threatenedsexual",
                   "CTQ_23", #_watchsexualthings",
                   "CTQ_24", #_molested",
                   "CTQ_27"), #_sexuallyabused"), 
                 # EN
                 c("CTQ_5", #_helpedfeelspecial",
                   "CTQ_7", #_feltloved",
                   "CTQ_13", #_familylookedout",
                   "CTQ_19", #_familyclose",
                   "CTQ_28"), #_familystrength"),
                 # PN
                 c("CTQ_1", #_notenoughtoeat",
                   "CTQ_2", #_protectme",
                   "CTQ_6", #_weardirtyclothes",
                   "CTQ_26", #_takemetodoctor",
                   "CTQ_4"), #_parentstoodrunk"),
                # Denial
                c("CTQ_10", #_nothingtochange",
                  "CTQ_16", #_perfectchildhood",
                  "CTQ_22")) #_bestfamily"))

subscale_info = list(scales = c("EA", "PA", "SA", "EN", "PN"), 
                     ctq_items = ctq_items)

ctq_SID <- ctq_df$tagid
ctq_df <- cbind(ctq_SID, ctq_df[, colnames(ctq_df) %in% unlist(ctq_items)])
colnames(ctq_df)[1] = "SID"

# items appear to have already been reverse-scored. if >1 missing per subscale, then the value is missing; if <2 per subscale, then value is mean imputed for that subscale. then add entire scale. 

ctq_missing_vector <- list()
ctq_subscale_imputed_sums <- list()

for (i in 1:length(subscale_info[[1]])){
  subscale = subscale_info[[1]][i]
  ctq_items = subscale_info[[2]][[i]]
  
  ctq_subscale_df <- cbind(ctq_SID, ctq_df[, colnames(ctq_df) %in% ctq_items])
  
  # count the number of nas
  num_ctq_nas <- ctq_subscale_df %>% 
    gather(., key = item, value = value, -ctq_SID) %>% 
    group_by(ctq_SID) %>% 
    summarise(total_ctq_na = sum(is.na(value)))

  # if the number of nas is 1 or 2, mean imput values
  ctq_na_vector <- which(num_ctq_nas$total_ctq_na == 1) #which(num_ctq_nas$total_ctq_na == 2))
  ctq_na_vector <- ctq_na_vector[order(ctq_na_vector)]
  
  # calculate mean values
  mean_ctq_subscale <- ctq_subscale_df[ctq_na_vector, ] %>% 
    gather(., key = item, value = value, -ctq_SID) %>% 
    group_by(ctq_SID) %>% 
    summarise(mean = mean(value, na.rm = TRUE))
  
  for (j in 1:length(ctq_na_vector)) {
    idx = ctq_na_vector[j]
    ctq_subscale_df[idx, which(is.na(ctq_subscale_df[idx, ]))] <- mean_ctq_subscale[j, ]$mean # if index is na replace w/ mean 
  } # output looks weird bc some went out to two decimal places, but checked manually it works!

  # sum scores imputed scores and replace with imputed values
  ctq_subscale_imputed_sums[[i]]  <- ctq_subscale_df %>% 
    gather(., key = item, value = response, -ctq_SID) %>% 
    group_by(ctq_SID) %>% 
    summarize(subscale_total = sum(response))
  
    # if the number of nas is 3 or more, save the SID number to be censored
  ctq_missing_vector[[i]] <- which(num_ctq_nas$total_ctq_na > 1)
}

ctq_subscale_imputed_sums_df <- purrr::reduce(ctq_subscale_imputed_sums, left_join, by = "ctq_SID")
colnames(ctq_subscale_imputed_sums_df) <- c("SID", subscale_info[[1]])

ctq_scores <- ctq_subscale_imputed_sums_df %>% 
  gather(., key = subscale, value = subscale_score, -SID) %>% 
  group_by(SID) %>% 
  summarise(ctq_total = round(sum(subscale_score), 0))

# load and clean pss - NOTE: THIS SEEMS VERY WRONG
pss_raw <- import(pss_file) 
pss_raw <- unique(pss_raw) # remove duplicated rows
pss_raw <- pss_raw[order(pss_raw$tagid), ] # order by subject ID

# based on the following output, it seems like row 42 is associated with Session 1 rather than session 2 and is less preferred
#> filter(PSS, tagid == "TAG055")
#   tagid       survey_name PSS_1 PSS_10 PSS_2 PSS_3 PSS_4 PSS_5 PSS_6 PSS_7 PSS_8 PSS_9
#1 TAG055 TAG - Sess 1 - V3     2      0     2     1     3     4     0     3     4     1
#2 TAG055 TAG - Sess 2 - V2     1      0     0     1     3     3     1     2     2     2
pss_raw <- pss_raw[-42, ]

survey_date <- pss_raw$survey_name
pss_sess2 <- grepl("Sess 2", pss_raw$survey_name)

pss_df <- pss_raw[, c("tagid", "PSS_1", "PSS_2", "PSS_3", "PSS_4", "PSS_5", "PSS_6", "PSS_7", "PSS_8", "PSS_9", "PSS_10")]
colnames(pss_df)[1] = "SID"

# how many NAs
num_pss_nas <- pss_df %>% 
  gather(., key = item, value = response, -SID) %>% 
  group_by(SID) %>% 
  summarise(total_pss_na = sum(is.na(response)))

# if the number of nas is 1, 2, or 3, mean imput values
pss_na_vector <- which(num_pss_nas$total_pss_na > 0 & num_pss_nas$total_pss_na < 4)  #0 & num_pss_nas$total_pss_na < 4)

pss_df[pss_na_vector, ] # print rows with 1, 2, or 3 NAs

# calculate mean imputed values
mean_pss_subscale <- pss_df[pss_na_vector, ] %>% 
  gather(., key = item, value = response, -SID) %>% 
  group_by(SID) %>% 
  summarise(mean = mean(response, na.rm = TRUE))

# replace pss values with subject means
for (j in 1:length(pss_na_vector)) {
  idx = pss_na_vector[j]
  pss_df[idx, which(is.na(pss_df[idx, ]))] <- mean_pss_subscale[j, ]$mean # if index is na replace w/ mean 
} # output looks weird bc some went out to two decimal places, but checked manually it works!

pss_scores <- pss_df %>% 
  gather(., key = item, value = response, -SID) %>% 
  group_by(SID) %>% 
  summarise(pss_total = round(sum(response), 0))

pss_scores$pss_sess2 <- sess2

# load and clean free lunch data
free_lunch_df <- import(paste0(data_dir, free_lunch_file))
free_lunch_df <- free_lunch_df[, c("TAG_ID", "W1_Kiddo_Free_Lunch")]
colnames(free_lunch_df) <- c("SID", "free_lunch")

stress_df <- full_join(ctq_scores, pss_scores, by = "SID") %>% 
  full_join(., free_lunch_df, by = "SID")

```

```{r save cleaned data}

if (save_clean_data = TRUE) {
  saveRDS(hormone_df, paste0(output_dir, "/hormone_df.RDS"))
  saveRDS(physical_mat_df, paste0(output_dir, "/physical_mat_df.RDS"))
  saveRDS(stress_df, paste0(output_dir, "/stress_df.RDS"))
}
```