---
title: "Puberty CFA version 2"
author: "Sam Chavez and Michelle Byrne"
date: "May 27, 2019"
output: html_document
---

## Set Working Directory
```{r Set Directory, message=FALSE, warning=FALSE, include=FALSE}
getwd()
#You should set this to the behavioral directory on the TAG file server 
workdir='Z:/dsnlab/TAG/behavior/' 
```

## Loading Libraries

```{r libraries, include = F}
library(tidyverse)
library(lavaan)
library(semPlot)
library(reshape2)
library(dplyr)
library(Hmisc)
library(corrplot)
library(lmtest)
library(nlsem)
```

## Load and Clean Data
```{r Load and Clean Data}
# Load Data
saliva <- read.csv(file.path(workdir,"Puberty/Saliva/Wave1/TAG_W1_Saliva_wide_cens_only4.csv", fsep=""))
hair <- read.csv(file.path(workdir,"Puberty/Hair/Wave1/TAG_W1_Hair_processed.csv", fsep=""))
qs <- read.csv(file.path(workdir,"Questionnaires/Puberty/Composite/TAG_W1_PubertyComposite.csv", fsep=""))

# Reformat & Merge Data

# Transforming Hair Data into Wide Format
hair <- dcast(hair, SID ~ hormone, value.var = "concentration_ln")
colnames(hair) <- c("SID","dhea_hair","estr_hair","test_hair")

# Getting rid of Saliva clutter
sal_dhea <- select(saliva, "SID", "sal_DHEA_conc_ln_w_1", "sal_DHEA_conc_ln_w_2", 
               "sal_DHEA_conc_ln_w_3", "sal_DHEA_conc_ln_w_4")
colnames(sal_dhea) <- c("SID","dhea1","dhea2","dhea3","dhea4")
sal_estr <- select(saliva, "SID", "sal_EST_conc_ln_w_1", "sal_EST_conc_ln_w_2", 
               "sal_EST_conc_ln_w_3", "sal_EST_conc_ln_w_4")
colnames(sal_estr) <- c("SID","estr1","estr2","estr3","estr4")
sal_test <- select(saliva, "SID", "sal_TEST_conc_ln_w_1", "sal_TEST_conc_ln_w_2", 
               "sal_TEST_conc_ln_w_3", "sal_TEST_conc_ln_w_4")
colnames(sal_test) <- c("SID","test1","test2","test3","test4")

# Re-Merging Saliva Data
saliva <- sal_dhea %>% full_join(sal_estr, by = "SID") %>% full_join(sal_test, by = "SID")

# Getting rid of Questionnaire Clutter
sr_qs <- select(qs, "SID", "PDS_F1", "PDS_F2", "PDS_F3", 
                "PDS_F4", "PDS_F6", "PBIP_1A", "PBIP_2A")
colnames(sr_qs) <- c("SID","PDS1","PDS2","PDS3",
                     "PDS4","PDS6","PBIP1","PBIP2")

# Making one big pretty data frame
hormones <- saliva %>% full_join(hair, by = "SID")
hormones_complete_E2hair <- filter(hormones, !is.na(estr_hair))
data <- hormones %>% full_join(sr_qs, by = "SID")

# Count missing data by variable
missing <- data.frame(matrix(ncol = 44, nrow = 1))
colnames(missing) <- c("na_dhea1","percna_dhea1","na_dhea2","percna_dhea2","na_dhea3",
                       "percna_dhea3","na_dhea4","percna_dhea4","na_estr1","percna_estr1",
                       "na_estr2","percna_estr2","na_estr3","percna_estr3","na_estr4",
                       "percna_estr4","na_test1","percna_test1","na_test2","percna_test2",
                       "na_test3","percna_test3","na_test4","percna_test4","na_dhea_hair",
                       "percna_dhea_hair","na_estr_hair","percna_estr_hair",
                       "na_test_hair","percna_test_hair","na_PDS1","percna_PDS1",
                       "na_PDS2","percna_PDS2","na_PDS3","percna_PDS3","na_PDS4",
                       "percna_PDS4","na_PDS6","percna_PDS6","na_PBIP1","percna_PBIP1",
                       "na_PBIP2","percna_PBIP2")
missing$na_dhea1 <- length(data$dhea1)-length(na.omit(data$dhea1))
missing$percna_dhea1 <- (missing$na_dhea1/length(data$dhea1))*100
missing$na_dhea2 <- length(data$dhea2)-length(na.omit(data$dhea2))
missing$percna_dhea2 <- (missing$na_dhea2/length(data$dhea2))*100
missing$na_dhea3 <- length(data$dhea3)-length(na.omit(data$dhea3))
missing$percna_dhea3 <- (missing$na_dhea3/length(data$dhea3))*100
missing$na_dhea4 <- length(data$dhea4)-length(na.omit(data$dhea4))
missing$percna_dhea4 <- (missing$na_dhea4/length(data$dhea4))*100
missing$na_estr1 <- length(data$estr1)-length(na.omit(data$estr1))
missing$percna_estr1 <- (missing$na_estr1/length(data$estr1))*100
missing$na_estr2 <- length(data$estr2)-length(na.omit(data$estr2))
missing$percna_estr2 <- (missing$na_estr2/length(data$estr2))*100
missing$na_estr3 <- length(data$estr3)-length(na.omit(data$estr3))
missing$percna_estr3 <- (missing$na_estr3/length(data$estr3))*100
missing$na_estr4 <- length(data$estr4)-length(na.omit(data$estr4))
missing$percna_estr4 <- (missing$na_estr4/length(data$estr4))*100
missing$na_test1 <- length(data$test1)-length(na.omit(data$test1))
missing$percna_test1 <- (missing$na_test1/length(data$test1))*100
missing$na_test2 <- length(data$test2)-length(na.omit(data$test2))
missing$percna_test2 <- (missing$na_test2/length(data$test2))*100
missing$na_test3 <- length(data$test3)-length(na.omit(data$test3))
missing$percna_test3 <- (missing$na_test3/length(data$test3))*100
missing$na_test4 <- length(data$test4)-length(na.omit(data$test4))
missing$percna_test4 <- (missing$na_test4/length(data$test4))*100

missing$na_dhea_hair <- length(data$dhea_hair)-length(na.omit(data$dhea_hair))
missing$percna_dhea_hair <- (missing$na_dhea_hair/length(data$dhea_hair))*100
missing$na_estr_hair <- length(data$estr_hair)-length(na.omit(data$estr_hair))
missing$percna_estr_hair <- (missing$na_estr_hair/length(data$estr_hair))*100
missing$na_test_hair <- length(data$test_hair)-length(na.omit(data$test_hair))
missing$percna_test_hair <- (missing$na_test_hair/length(data$test_hair))*100

missing$na_PDS1 <- length(data$PDS1)-length(na.omit(data$PDS1))
missing$percna_PDS1 <- (missing$na_PDS1/length(data$PDS1))*100
missing$na_PDS2 <- length(data$PDS2)-length(na.omit(data$PDS2))
missing$percna_PDS2 <- (missing$na_PDS2/length(data$PDS2))*100
missing$na_PDS3 <- length(data$PDS3)-length(na.omit(data$PDS3))
missing$percna_PDS3 <- (missing$na_PDS3/length(data$PDS3))*100
missing$na_PDS4 <- length(data$PDS4)-length(na.omit(data$PDS4))
missing$percna_PDS4 <- (missing$na_PDS4/length(data$PDS4))*100
missing$na_PDS6 <- length(data$PDS6)-length(na.omit(data$PDS6))
missing$percna_PDS6 <- (missing$na_PDS6/length(data$PDS6))*100
missing$na_PBIP1 <- length(data$PBIP1)-length(na.omit(data$PBIP1))
missing$percna_PBIP1 <- (missing$na_PBIP1/length(data$PBIP1))*100
missing$na_PBIP2 <- length(data$PBIP2)-length(na.omit(data$PBIP2))
missing$percna_PBIP2 <- (missing$na_PBIP2/length(data$PBIP2))*100

# Specifying PDS & PBIP variables as ordinal
data_ord <- data
data_menarche <- data
data_mpbip <- data
data_ord[, 17:23] <- lapply(data_ord[, 17:23], ordered)
data_menarche$PDS6 <- ordered(data_menarche$PDS6)
data_mpbip[, 21:23] <- lapply(data_mpbip[, 21:23], ordered)
```

## PART 1: SELF-REPORT MODELS ONLY 
```{r SRMs}

# Define SRM1 - Self-Report Only with 1 Puberty Factor. No covariances

sr1 <- "
#Latent Neuroendocrine Systems
puberty =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2
"
# Define SRM3 - Self-Report Only with 1 Puberty Factor. WITH covariances. No covar on PDS6
sr3 <- "
#Latent Neuroendocrine Systems
puberty =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#Covariances for questionnaires
PDS1 ~~ PDS2 + PDS3 + PDS4
PDS2 ~~ PDS3 + PDS4
PDS3 ~~ PDS4
PBIP1 ~~ PBIP2
"

#Other stuff not using for now
#model_sr1_noPDS1 <- "
##Latent Neuroendocrine Systems
#puberty =~ PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

##Covariances for questionnaires
#PDS2 ~~ PDS3 + PDS4
#PDS3 ~~ PDS4
#PBIP1 ~~ PBIP2
#"

#model_sr1_noPDS1_nocov <- "
##Latent Neuroendocrine Systems
#puberty =~ PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2
#"

#model_sr1_nocov_noPBIP <- "
##Latent Neuroendocrine Systems
#puberty =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6
#"

# Define SRM2 - Self-Report Only with 2 Puberty Factors (Adrenal & Gonadal). No covariances.

sr2 <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS1 + PDS4 + PDS6 + PBIP1
"

# Define SRM4 - Self-Report Only with 2 Puberty Factors (Adrenal & Gonadal). WITH covariances.
sr4 <- "
#Latent Neuroendocrine Systems
adrenal =~ PDS2 + PDS3 + PBIP2
gonadal =~ PDS1 + PDS4 + PDS6 + PBIP1

#Covariances for questionnaires (minus pds6)
PDS1 ~~ PDS2 + PDS3 + PDS4
PDS2 ~~ PDS3 + PDS4
PDS3 ~~ PDS4
PBIP1 ~~ PBIP2
"

#Other stuff not using for now
#model_sr2_noPDS1 <- "
##Latent Neuroendocrine Systems
#adrenal =~ PDS2 + PDS3 + PBIP2
#gonadal =~ PDS4 + PDS6 + PBIP1

##Covariances for questionnaires
#PDS2 ~~ PDS3 + PDS4
#PDS3 ~~ PDS4
#PBIP1 ~~ PBIP2
#"

#model_sr2_noPDS1_nocov <- "
##Latent Neuroendocrine Systems
#adrenal =~ PDS2 + PDS3 + PBIP2
#gonadal =~ PDS4 + PDS6 + PBIP1
#"

#model_sr2_nocov_noPBIP <- "
##Latent Neuroendocrine Systems
#adrenal =~ PDS2 + PDS3
#gonadal =~ PDS1 + PDS4 + PDS6
#"



# ** Fit Self-Report CFAs (ordinal data) - PML - USE THIS **
fit_sr1_pml <- cfa(sr1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr2_pml <- cfa(sr2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr3_pml <- cfa(sr3, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

fit_sr4_pml <- cfa(sr4, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

#fit_model_sr1_pml_noPDS1 <- cfa(model_sr1_noPDS1, data = data, estimator = "PML",
#                      missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6","PBIP1","PBIP2"))
#fit_model_sr1_pml_noPDS1_nocov <- cfa(model_sr1_noPDS1_nocov, data = data, 
#                                      estimator = "PML",
#                      missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6","PBIP1","PBIP2"))
#
#fit_model_sr1_pml_nocov_noPBIP <- cfa(model_sr1_nocov_noPBIP, data = data, estimator = "PML", 
#                      missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6"))
#
#fit_model_sr2_pml_noPDS1 <- cfa(model_sr2_noPDS1, data = data, estimator = "PML", 
#                      missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6","PBIP1","PBIP2")
#
#fit_model_sr2_pml_noPDS1_nocov <- cfa(model_sr2_noPDS1_nocov, data = data, 
#                                      estimator = "PML", 
#                      missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6","PBIP1","PBIP2"))
#fit_model_sr2_pml_nocov_noPBIP <- cfa(model_sr2_nocov_noPBIP, data = data, estimator = "PML", 
#                      missing = "available.cases", verbose = T,  
#                     ordered = c("PDS1","PDS2","PDS3","PDS4",
#                                 "PDS6")) # Note this comes up with the dread pirate NOT POSITIVE DEFINITE

# Fit Self-Report CFAs (continuous data)
#fit_model_sr1_cont <- cfa(model_sr1, data = data, 
#                     missing = "pairwise",
#                     verbose = T)
#fit_model_sr1_cont_nocov <- cfa(model_sr1_nocov, data = data, 
#                     missing = "pairwise",
#                     verbose = T)
#fit_model_sr1_cont_noPDS1 <- cfa(model_sr1_noPDS1, data = data, 
#                     missing = "pairwise",
#                     verbose = T)
#fit_model_sr1_cont_noPDS1_nocov <- cfa(model_sr1_noPDS1_nocov, data = data, 
#                     missing = "pairwise",
#                     verbose = T)
#
#fit_model_sr2_cont <- cfa(model_sr2, data = data, 
#                        missing = "pairwise",
#                        verbose = T)
#fit_model_sr2_cont_nocov <- cfa(model_sr2_nocov, data = data, 
#                        missing = "pairwise",
#                        verbose = T)
#fit_model_sr2_cont_noPDS1 <- cfa(model_sr2_noPDS1, data = data, 
#                     missing = "pairwise",
#                     verbose = T)
#fit_model_sr2_cont_noPDS1_nocov <- cfa(model_sr2_noPDS1_nocov, data = data, 
#                     missing = "pairwise",
#                     verbose = T)


# Model Stats & Comparison 

#Do we need covariances between items of the same questionnaire?

#anova(fit_model_sr1_ord, fit_model_sr1_ord_nocov)
#anova(fit_model_sr1_ord_noPDS1, fit_model_sr1_ord_noPDS1_nocov)
anova(fit_sr3_pml, fit_sr1_pml) # 1 factor models
#anova(fit_model_sr1_pml_noPDS1, fit_model_sr1_pml_noPDS1_nocov)
#anova(fit_model_sr2_ord, fit_model_sr2_ord_nocov)
#anova(fit_model_sr2_ord_noPDS1, fit_model_sr2_ord_noPDS1_nocov)
anova(fit_sr4_pml, fit_sr2_pml) # 2 factor models
#anova(fit_model_sr2_pml_noPDS1, fit_model_sr2_pml_noPDS1_nocov)
#For all models, adding covariances for self-report Qs does not increase model fit indices.


#Should we include PDS1?
#fitmeasures(fit_model_sr1_ord_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#summary(fit_model_sr1_ord_nocov, fit.measures = T, standardized = T)
#fitmeasures(fit_model_sr1_ord_noPDS1_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#fitmeasures(fit_model_sr1_pml_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#fitmeasures(fit_model_sr1_pml_noPDS1_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#model with PDS1 is slightly better for most fit indices in AG models
#fitmeasures(fit_model_sr2_ord_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#summary(fit_model_sr2_ord_nocov, fit.measures = T, standardized = T)
#
#fitmeasures(fit_model_sr2_ord_noPDS1_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#fitmeasures(fit_model_sr2_pml_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#fitmeasures(fit_model_sr2_pml_noPDS1_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#model with PDS1 is slightly better for most fit indices in P models
#leaving PDS1 in the model from this point forward


#Is self-reported puberty better captured by A+G or P? 

#WLSMV - don't use
#summary(fit_model_sr1_ord_nocov, fit.measures = T, standardized = T)
#summary(fit_model_sr2_ord_nocov, fit.measures = T, standardized = T)
#anova(fit_model_sr1_ord_nocov, fit_model_sr2_ord_nocov)
#lavTestLRT(fit_model_sr1_ord_nocov, fit_model_sr2_ord_nocov)
#fitmeasures(fit_model_sr1_ord_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#fitmeasures(fit_model_sr2_ord_nocov,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
#AG fits better than P for model with NO covariances between items of the same questionnaire,
#data treated as ordinal, and wlsmv estimator (p<0.05)

# One vs 2 factor for models - NO covariances
summary(fit_sr1_pml, fit.measures = T, standardized = T)
summary(fit_sr2_pml, fit.measures = T, standardized = T)

lavTestLRT(fit_sr1_pml, fit_sr2_pml)

fitmea_sr1_pml <- fitmeasures(fit_sr1_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
fitmea_sr2_pml <- fitmeasures(fit_sr2_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
#AG fits better than P for model with NO covariances between items of the same questionnaire,
#data treated as ordinal, and pml estimator (p=0.09)

# One vs 2 factor for models - WITH covariances
summary(fit_sr3_pml, fit.measures = T, standardized = T)
summary(fit_sr4_pml, fit.measures = T, standardized = T)

lavTestLRT(fit_sr3_pml, fit_sr4_pml)

fitmea_sr3_pml <- fitmeasures(fit_sr3_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))
fitmea_sr4_pml <- fitmeasures(fit_sr4_pml,
            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

```


## Step 2: Hormone Models - Saliva + Hair. All have no equality constraints. 
```{r HMs}
##########

# First we run all four models WITH BOTH latent hormone (DHEA, T, E2) and neuroendocrine (ADR, GON, PUB) variables. Even though the one- and two-factor models are equivalent

##########

# Define HM1 - one factor, no covariances, hair + saliva
hm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
puberty =~ dhea + estr + test

"

# Fit HM1 - can only get MLR to converge (? check this):

fit_hm1 <- cfa(hm1, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") #even with MLR, some estimated lv variances are negative

fit_hm1_pml <- cfa(hm1, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr") #the optimizer warns that a solution has NOT been found!

# Summary Stats for HM1
summary(fit_hm1_pml, fit.measures = T, standardized = T)
# below doesn't work bc didn't converge
# fitmea_hm1_pml <- fitMeasures(fit_hm1_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

# Pictoral Representation of HM1
#semPaths(fit_hm1)


# Define HM2 - two factors, no covariances, hair + saliva
hm2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
adrenal =~ dhea + test

"

# Fit HM2 - can only get PML to converge:

#fit_hm2 <- cfa(hm2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") #the optimizer warns that a solution has NOT been found!

fit_hm2_pml <- cfa(hm2, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr") # some dodgy stuff still happens but you can still get some estimates

# Summary Stats for HM2
summary(fit_hm2_pml, fit.measures = T, standardized = T)
fitmea_hm2_pml <- fitMeasures(fit_hm2_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

# Pictoral Representation of HM2
semPaths(fit_hm2_pml)

# Define HM3 - one factor, WITH covariances, hair + saliva
hm3 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
puberty =~ dhea + estr + test

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM3
# fit_hm3 <- cfa(hm3, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr")
fit_hm3_pml <- cfa(hm3, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HM3
# summary(fit_hm3, fit.measures = T, standardized = T)
# fitMeasures(fit_hm3, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

summary(fit_hm3_pml, fit.measures = T, standardized = T)
fitmea_hm3_pml <- fitMeasures(fit_hm3_pml,
                              fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue","rmsea"))

# Pictoral Representation of HM3
semPaths(fit_hm3_pml)

# Define HM4 - two factors, WITH covariances, hair + saliva 
hm4 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Hormone Variables
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Latent Neuroendocrine Systems
adrenal =~ dhea + test

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM4 - only PML converges:

#fit_hm4 <- cfa(hm4, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") #the optimizer warns that a solution has NOT been found! 
fit_hm4_pml <- cfa(hm4, data = hormones, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for HM4
#summary(fit_hm4, fit.measures = T, standardized = T)
#fitMeasures(fit_hm4, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm4_pml, fit.measures = T, standardized = T)
fitmea_hm4_pml <- fitMeasures(fit_hm4_pml, 
                              fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))

# Pictoral Representation of HM4
semPaths(fit_hm4_pml)

#lavTestLRT(fit_hm1_pml, fit_hm3_pml)
lavTestLRT(fit_hm2_pml, fit_hm4_pml)

#lavTestLRT(fit_hm1_pml, fit_hm2_pml)
#lavTestLRT(fit_hm3_pml, fit_hm4_pml)

##########

# Second, because no HMs above worked whatsoever, we run all four models without the latent hormone (DHEA, T, E2) variables and everything loads directly onto neuroendocrine (ADR, GON, PUB) variables. These are HMv2 (hormone models version 2). Currently this is what's reported.

##########

# Define HM1v2 - one factor, no covariances, hair + saliva
hm1v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + dhea_hair + estr_hair + test_hair

"

# Fit HM1v2:
fit_hm1v2_pml <- cfa(hm1v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for HM1
#summary(fit_hm1v2, fit.measures = T, standardized = T)
#fitMeasures(fit_hm1v2,
#            fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm1v2_pml, fit.measures = T, standardized = T)
fitmea_hm1v2_pml <- fitMeasures(fit_hm1v2_pml,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HM1
# semPaths(fit_hm1v2)
semPaths(fit_hm1v2_pml)

# Define HM2 - two factors, no covariances, hair + saliva
hm2v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test + dhea_hair + test_hair
gonadal =~ sal_estr + estr_hair
"

# Fit HM2v2:
# fit_hm2v2 <- cfa(hm2v2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") 
fit_hm2v2_pml <- cfa(hm2v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for HM2v2
# summary(fit_hm2v2, fit.measures = T, standardized = T)
# fitMeasures(fit_hm2v2, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm2v2_pml, fit.measures = T, standardized = T)
fitmea_hm2v2_pml <- fitMeasures(fit_hm2v2_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of HM2v2
#semPaths(fit_hm2v2)
semPaths(fit_hm2v2_pml)

# Define HM3v2 - one factor, WITH covariances, hair + saliva
hm3v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + dhea_hair + estr_hair + test_hair

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM3v2
# fit_hm3v2 <- cfa(hm3v2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr")
fit_hm3v2_pml <- cfa(hm3v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HM3
# summary(fit_hm3v2, fit.measures = T, standardized = T)
# fitMeasures(fit_hm3v2, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm3v2_pml, fit.measures = T, standardized = T)
fitmea_hm3v2_pml <- fitMeasures(fit_hm3v2_pml,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HM3v2
# semPaths(fit_hm3v2)
semPaths(fit_hm3v2_pml)

# Define HM4v2 - two factors, WITH covariances, hair + saliva 
hm4v2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test + dhea_hair + test_hair
gonadal =~ sal_estr + estr_hair

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair Sample 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit HM4v2:
# fit_hm4v2 <- cfa(hm4v2, data = hormones, missing = "ML", estimator = "MLR", se = "robust.mlr") 
fit_hm4v2_pml <- cfa(hm4v2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for HM4v2
# summary(fit_hm4v2, fit.measures = T, standardized = T)
# fitMeasures(fit_hm4v2, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea"))
summary(fit_hm4v2_pml, fit.measures = T, standardized = T)
fitmea_hm4v2_pml <- fitMeasures(fit_hm4v2_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of HM4
# semPaths(fit_hm4v2)
semPaths(fit_hm4v2_pml)

#Compare models
lavTestLRT(fit_hm1v2_pml, fit_hm3v2_pml) # 1 factor with or w/o covar? p=0.07913
lavTestLRT(fit_hm2v2_pml, fit_hm4v2_pml) # 2 factor with or w/o covar? p=0.3381

lavTestLRT(fit_hm1v2_pml, fit_hm2v2_pml) # 1 or 2 factor w/o covar? p=0.3786
lavTestLRT(fit_hm3v2_pml, fit_hm4v2_pml) # 1 or 2 factor with covar? p=0.3625

```

## Step 3: Post hoc Hormone Models 1 (Reduced hormone models) - Hair E2 ONLY + Saliva (no hair DHEA or hair T)
```{r RHMs}

# Define RHM1 - one factor, no covariances, hair E2 only + saliva
rhm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + estr_hair 

"

# Fit RHM1:
fit_rhm1_pml <- cfa(rhm1, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for RHM1
summary(fit_rhm1_pml, fit.measures = T, standardized = T)
fitmea_rhm1_pml <- fitMeasures(fit_rhm1_pml,
                                fit.measures = c("cfi","ecvi","mfi", 
                                                 "chisq", "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HM1
semPaths(fit_rhm1_pml)

# Define RHM2 - two factors, no covariances, hair E2 only + saliva
rhm2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test 
gonadal =~ sal_estr + estr_hair
"

# Fit RHM2:
fit_rhm2_pml <- cfa(rhm2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for RHM2
summary(fit_rhm2_pml, fit.measures = T, standardized = T)
fitmea_rhm2_pml <- fitMeasures(fit_rhm2_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of RHM2
semPaths(fit_rhm2_pml)

# Define RHM3 - one factor, WITH covariances, hair E2 only + saliva
rhm3 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
puberty =~ sal_dhea + sal_estr + sal_test + estr_hair

#Covariances for Saliva Sample Day 
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit RHM3
fit_rhm3_pml <- cfa(rhm3, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for RHM3
summary(fit_rhm3_pml, fit.measures = T, standardized = T)
fitmea_rhm3_pml <- fitMeasures(fit_rhm3_pml,
                                fit.measures = c("cfi","ecvi","mfi", "chisq", 
                                                 "pvalue", "rmsea", "srmr"))

# Pictoral Representation of RHM3
semPaths(fit_rhm3_pml)

# Define RHM3 - two factors, WITH covariances, hair E2 only + saliva 
rhm4 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Latent Neuroendocrine Systems
adrenal =~ sal_dhea + sal_test 
gonadal =~ sal_estr + estr_hair

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit RHM4:
fit_rhm4_pml <- cfa(rhm4, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr") 

# Summary Stats for RHM4
summary(fit_rhm4_pml, fit.measures = T, standardized = T)
fitmea_rhm4_pml <- fitMeasures(fit_rhm4_pml, 
                                fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue",
                                                 "rmsea", "srmr"))

# Pictoral Representation of RHM4
semPaths(fit_rhm4_pml)

#Compare models
lavTestLRT(fit_rhm1_pml, fit_rhm3_pml) # 1 factor with or w/o covar? 
lavTestLRT(fit_rhm2_pml, fit_rhm4_pml) # 2 factor with or w/o covar? 

lavTestLRT(fit_rhm1_pml, fit_rhm2_pml) # 1 or 2 factor w/o covar? 
lavTestLRT(fit_rhm3_pml, fit_rhm4_pml) # 1 or 2 factor with covar? 
```


## Step 4 - Post hoc hormone Models 2 - Hair Predicts Saliva
```{r Hair Predicts Saliva}
# Define HSM1 - No methods factors
hsm1 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Regressions
sal_dhea ~ dhea_hair
sal_estr ~ estr_hair
sal_test ~ test_hair

#Covariances for Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4
"
# Define HSM2 (hair saliva model with method factors)
hsm2 <- "
#Latent Saliva Variables
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Regressions
sal_dhea ~ dhea_hair
sal_estr ~ estr_hair
sal_test ~ test_hair

#Covariances for Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Methods Factors
hair =~ dhea_hair + estr_hair + test_hair
saliva =~ dhea1 + dhea2 + dhea3 + dhea4 + estr1 + estr2 + estr3 + estr4 + test1 + test2 + test3 + test4

#Set Latent Var Covariances to Zero
hair ~~ 0*saliva + 0*sal_dhea + 0*sal_estr + 0*sal_test
saliva ~~ 0*sal_dhea + 0*sal_estr + 0*sal_test
"

# Fit HSM1 All Data
fit_hsm1_pml <- cfa(hsm1, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HSM1
summary(fit_hsm1_pml, fit.measures = T, standardized = T) 
fitmea_hsm1_pml <- fitMeasures(fit_hsm1_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

semPaths(fit_hsm1_pml)

# Fit Model HSM2
fit_hsm2_pml <- cfa(hsm2, data = data, missing = "available.cases", estimator = "PML", se = "robust.mlr")

# Summary Stats for HSM2
summary(fit_hsm2_pml, fit.measures = T, standardized = T) 
fitmea_hsm2_pml <- fitMeasures(fit_hsm2_pml, fit.measures = c("cfi","ecvi","mfi", "chisq", "pvalue", "rmsea", "srmr"))

# Pictoral Representation of HSMs
semPaths(fit_hsm1_pml)
semPaths(fit_hsm2_pml)

# Comparing Model Fits - wait these don't work
lavTestLRT(fit_hsm1_pml, fit_hsm2_pml)

```

Step 5: dracarys
```{r FMs}
##########

# These are the four initial full models but later we decided to only run 2 and only use hair E2 (see versions2 below)

##########

#Define Full Model (FM)1 - one factor, including hair, second level factors (hormone and self-report)
fm1 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Hormones (Saliva + Hair) - Level 2
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ dhea + estr + test

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair

"

# Fit FM1 - using PML (takes awhile to run - In past we have also used estimator = "WLSMV", missing = "pairwise")
fit_fm1_pml <- cfa(fm1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for Full Model 1
summary(fit_fm1_pml, fit.measures = T, standardized = T) 
fitmea_fm1_pml <- fitmeasures(fit_fm1_pml,
            fit.measures = c("cfi","ecvi","mfi")) 

# Pictoral Representation of Full Model 1
semPaths(fit_fm1_pml)


# Define Full Model (FM)2 - two factor, including hair, second level factors (hormone and self-report)
fm2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Hormones (Saliva + Hair) - Level 2
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ dhea + test + adrenal_sr
gonadal =~ estr + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit FM2
fit_fm2_pml <- cfa(fm2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for FM2
summary(fit_fm2_pml, fit.measures = T, standardized = T)
fitmea_fm2_pml <- fitmeasures(fit_fm2_pml, fit.measures = c("cfi","ecvi","mfi"))
fit_fm2_pml_parest <- parameterEstimates(fit_fm2_pml)
lavaan:::ctr_pml_plrt(fit_fm2_pml)

# Pictoral Representation of FM2
semPaths(fit_fm2_pml)

#Compare two- and one-factor models that include hair
anova(fit_fm2_pml, fit_fm1_pml) # spits out stupid numbers
lrtest(fit_fm2_pml, fit_fm1_pml)


# Define Full Model 3 - One factor, No Hair Variables 
fm3 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS2 + PDS3 + PDS1 + PDS4 + PDS6 + PBIP1 + PBIP2

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
pub_bio =~ sal_dhea + sal_estr + sal_test

#Puberty
puberty =~ pub_sr + pub_bio

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4
"

# Fit Full Model 3
fit_fm3_pml <- cfa(fm3, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for Full Model 3
summary(fit_fm3_pml, fit.measures = T, standardized = T)
fitmea_fm3_pml <- fitmeasures(fit_fm3_pml,
            fit.measures = c("cfi","ecvi","mfi"))

# Pictoral Representation of Full Model 3
semPaths(fit_fm3_pml)

# Compare one factor with and without hair
# anova(fit_fm1_pml, fit_fm3_pml) # doesn't work I'm guessing cause you can't compare models with different number of observed variables


# Define Full Model 4 - Two-factor, No Hair Variables
fm4 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Neuroendocrine Systems
a_bio =~ sal_dhea + sal_test
adrenal =~ a_bio + adrenal_sr
gonadal =~ sal_estr + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Set some latent var covars to zero
a_bio ~~ 0*gonadal
"

# Fit Full Model 4
fit_fm4_pml <- cfa(fm4, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for Full Model 4
summary(fit_fm4_pml, fit.measures = T, standardized = T)
fitmea_fm4_pml <- fitmeasures(fit_fm4_pml, fit.measures = c("cfi","ecvi","mfi"))

# Pictoral Representation of Full Model 4
semPaths(fit_fm4_pml)

# Compare 2 factor with and without hair - wait I don't think you can do this
# anova(fit_fm4_pml, fit_fm2_pml)
# Compare one and two factor without hair
anova(fit_fm4_pml, fit_fm3_pml) # spits out stupid numbers

##########

# Now do two more full models (versions 2) that include only Hair E2 and all saliva (this is in current paper):

##########

# Define Full Model (FM)1v2 - one factor, including hair E2 only and all saliva, second level factors for self-report only:

fm1v2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
pub_sr =~ PDS1 + PDS2 + PDS3 + PDS4 + PDS6 + PBIP1 + PBIP2

#BioVars
pub_bio =~ sal_dhea + sal_estr + sal_test + estr_hair

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
puberty =~ pub_sr + pub_bio

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit FM1v2 - using PML 
fit_fm1v2_pml <- cfa(fm1v2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for Full Model 1 v2
summary(fit_fm1v2_pml, fit.measures = T, standardized = T) 
fitmea_fm1v2_pml <- fitmeasures(fit_fm1v2_pml,
            fit.measures = c("cfi","ecvi","mfi")) 

# Pictoral Representation of Full Model 1 v2
semPaths(fit_fm1v2_pml)

# Define Full Model (FM)2v2 - two factor, including hair, second level factors (hormone and self-report)
fm2v2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1
adrenal_bio =~ sal_dhea + sal_test
gonadal_bio =~ sal_estr + estr_hair

#Neuroendocrine Systems (Saliva + Hair + Qs) - Level 3
adrenal =~ adrenal_bio + adrenal_sr
gonadal =~ gonadal_bio + gonadal_sr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit FM2v2

fit_fm2v2_pml <- cfa(fm2v2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS1","PDS2","PDS3","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for FM2v2
summary(fit_fm2v2_pml, fit.measures = T, standardized = T)
fitmea_fm2v2_pml <- fitmeasures(fit_fm2v2_pml, fit.measures = c("cfi","ecvi","mfi"))
fit_fm2v2_pml_parest <- parameterEstimates(fit_fm2v2_pml)
lavaan:::ctr_pml_plrt(fit_fm2v2_pml)

# Pictoral Representation of FM2v2
semPaths(fit_fm2v2_pml)

#Compare two- and one-factor models that include E2 hair only and all saliva
anova(fit_fm2v2_pml, fit_fm1v2_pml) 
lrtest(fit_fm2v2_pml, fit_fm1v2_pml)



```


```{r Bio predicts Self-Report SEM}

##########

# Old SEMs with all the hairs (1 & 2) and none of the hairs (3 & 4)

##########

# Define SEM Model 1 - Does hormone (saliva + hair) PUB predict Self-Reported PUB?
sem1 <- "
#Latent Variables

#Saliva
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Hormones (Saliva + Hair) - Level 2
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair
test =~ sal_test + test_hair

#Bio Puberty
bio_puberty =~ dhea + estr + test

#Self-Report Puberty
sr_puberty =~ PDS2 + PDS3 + PDS1 + PDS4 + PDS6 + PBIP1 + PBIP2

#Regressions
sr_puberty ~ bio_puberty

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Define SEM Model 2 - Does hormone (saliva + hair) ADR and GON predict Self-Reported ADR and GON?
sem2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Hormones (Saliva + Hair) - Level 2
dhea =~ sal_dhea + dhea_hair
estr =~ sal_estr + estr_hair 
test =~ sal_test + test_hair

#bio Adrenal
bio_adrenal =~ dhea + test

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Regressions
adrenal_sr ~ bio_adrenal
gonadal_sr ~ estr

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

#Covariances for Hair 
dhea_hair ~~ estr_hair + test_hair
estr_hair ~~ test_hair
"

# Fit SEM 1
fit_sem1_pml <- cfa(sem1, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for SEM 1
summary(fit_sem1_pml, fit.measures = T, standardized = T)
fitmea_sem1_pml <- fitmeasures(fit_sem1_pml,
            fit.measures = c("cfi","ecvi","mfi","pvalue"))

# Pictoral Representation of SEM 1
semPaths(fit_sem1_pml)

# Fit SEM 2
fit_sem2_pml <- cfa(sem2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for SEM 2
summary(fit_sem2_pml, fit.measures = T, standardized = T)
fitmea_sem2_pml <- fitmeasures(fit_sem2_pml,
            fit.measures = c("cfi","ecvi","mfi","pvalue"))

# Pictoral Representation of SEM 2
semPaths(fit_sem2_pml)

#Comparing Model Fits
anova(fit_sem1_pml, fit_sem2_pml) # this tells me stupid stuff

# Define SEM Model 3 - Does Salivary (without hair) PUB predict Self-Reported PUB?
sem3 <- "
#Latent Variables

#Saliva
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Bio Puberty
bio_puberty =~ sal_dhea + sal_estr + sal_test

#Self-Report Puberty
sr_puberty =~ PDS2 + PDS3 + PDS1 + PDS4 + PDS6 + PBIP1 + PBIP2

#Regressions
sr_puberty ~ bio_puberty

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4
"

# Define SEM Model 4 - Does Salivary (without hair) ADR and GON predict Self-Reported ADR and GON?
sem4 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_gonadal =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Saliva Adrenal
sal_adrenal =~ sal_dhea + sal_test

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Regressions
adrenal_sr ~ sal_adrenal
gonadal_sr ~ sal_gonadal

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4
"


# Fit SEM 3
fit_sem3_pml <- cfa(sem3, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for SEM 3
summary(fit_sem3_pml, fit.measures = T, standardized = T)
fitmea_sem3_pml <- fitmeasures(fit_sem3_pml,
            fit.measures = c("cfi","ecvi","mfi","pvalue"))

# Pictoral Representation of SEM3
semPaths(fit_sem3_pml)

# Fit SEM 4
fit_sem4_pml <- cfa(sem4, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2")) # the dread pirate positive definite

# Summary Stats for SEM 4
summary(fit_sem4_pml, fit.measures = T, standardized = T)
fitmea_sem4_pml <- fitmeasures(fit_sem4_pml,
            fit.measures = c("cfi","ecvi","mfi","pvalue"))

# Pictoral Representation of SEM  4
semPaths(fit_sem4_pml)

#Comparing Model Fits
anova(fit_sem3_pml, fit_sem4_pml)

##########

# Now do SEM 1 and 2 again (SEM1v2 and SEM2v2) - but only with hair E2

##########

#define SEM1v2 - - Does hormone (saliva + hair E2 only) PUB predict Self-Reported PUB?

sem1v2 <- "
#Latent Variables

#Saliva
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#Bio Puberty
bio_puberty =~ sal_dhea + sal_estr + sal_test + estr_hair

#Self-Report Puberty
sr_puberty =~ PDS2 + PDS3 + PDS1 + PDS4 + PDS6 + PBIP1 + PBIP2

#Regressions
sr_puberty ~ bio_puberty

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Define SEM2v2 - Does hormone (saliva + hair E2 only) ADR and GON predict Self-Reported ADR and GON?
sem2v2 <- "
#Latent Variables

#Saliva - Level 1
sal_dhea =~ dhea1 + dhea2 + dhea3 + dhea4
sal_estr =~ estr1 + estr2 + estr3 + estr4
sal_test =~ test1 + test2 + test3 + test4

#bio Gonadal
bio_gonadal =~ sal_estr + estr_hair 

#bio Adrenal
bio_adrenal =~ sal_dhea + sal_test

#Self-Report
adrenal_sr =~ PDS2 + PDS3 + PBIP2
gonadal_sr =~ PDS1 + PDS4 + PDS6 + PBIP1

#Regressions
adrenal_sr ~ bio_adrenal
gonadal_sr ~ bio_gonadal

#Covariances for Saliva Sample Day
dhea1 ~~ estr1 + test1
estr1 ~~ test1
dhea2 ~~ estr2 + test2
estr2 ~~ test2
dhea3 ~~ estr3 + test3
estr3 ~~ test3
dhea4 ~~ estr4 + test4
estr4 ~~ test4

"

# Fit SEM 1v2
fit_sem1v2_pml <- cfa(sem1v2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for SEM 1v2
summary(fit_sem1v2_pml, fit.measures = T, standardized = T)
fitmea_sem1v2_pml <- fitmeasures(fit_sem1v2_pml,
            fit.measures = c("cfi","ecvi","mfi","pvalue","srmr"))

# Pictoral Representation of SEM 1v2
semPaths(fit_sem1v2_pml)

# Fit SEM 2v2
fit_sem2v2_pml <- cfa(sem2v2, data = data, estimator = "PML", 
                      missing = "available.cases", verbose = T,  
                     ordered = c("PDS2","PDS3","PDS1","PDS4",
                                 "PDS6","PBIP1","PBIP2"))

# Summary Stats for SEM 2v2
summary(fit_sem2v2_pml, fit.measures = T, standardized = T)
fitmea_sem2v2_pml <- fitmeasures(fit_sem2v2_pml,
            fit.measures = c("cfi","ecvi","mfi","pvalue","srmr"))

# Pictoral Representation of SEM 2v2
semPaths(fit_sem2v2_pml)

#Comparing Model Fits
anova(fit_sem1v2_pml, fit_sem2v2_pml) 

```

```{r}
#Extracting Latent Variable Estimates per Subject
sem1_extract_vars <- lavPredict(fit_sem1v2_pml)
sem2_extract_vars <- lavPredict(fit_sem2v2_pml)

#Correlation Matrices for Latent Var Estimates
sem1_cor <- cor(sem1_extract_vars)
sem1_p_bio_sr_r2 <- (sem1_cor[5,4])*(sem1_cor[5,4])
sem2_cor <- cor(sem2_extract_vars)
sem2_a_bio_sr_r2 <- (sem2_cor[6,5])*(sem2_cor[6,5])
sem2_g_bio_sr_r2 <- (sem2_cor[7,4])*(sem2_cor[7,4])

# "P" bio with hair predict "P" self-report
sem1_p_plot <- plot(sem1_extract_vars[,"sr_puberty"] ~ sem1_extract_vars[,"bio_puberty"], ylab = "Estimates for Self-Reported Puberty", xlab = "Estimates for Hormone Puberty") + title(main = "Extracted Latent Variables:\n One-factor Puberty") + abline(lm(sem1_extract_vars[,"sr_puberty"] ~ sem1_extract_vars[,"bio_puberty"])) + 
  text(x=1.4, y=-1.2, labels = bquote(italic(R)^2 == .(format(sem1_p_bio_sr_r2))))

# "A" bio with hair predict "A" self-report 
sem2_a_plot <- plot(sem2_extract_vars[,"adrenal_sr"] ~ sem2_extract_vars[,"bio_adrenal"], ylab = "Estimates for Self-Reported Adrenarche", xlab = "Estimates for Hormone Adrenarche") + title(main = "Extracted Latent Variables:\n Two-factor Adrenarche") + abline(lm(sem2_extract_vars[,"adrenal_sr"] ~ sem2_extract_vars[,"bio_adrenal"])) + 
  text(x=1.45, y=-1.25, labels = bquote(italic(R)^2 == .(format(sem2_a_bio_sr_r2))))

# "G" bio with hair predict "G" self-report 
sem2_g_plot <- plot(sem2_extract_vars[,"gonadal_sr"] ~ sem2_extract_vars[,"bio_gonadal"], ylab = "Estimates for Self-Reported Gonadarche", xlab = "Estimates for Hormone Gonadarche") + title(main = "Extracted Latent Variables:\n Two-factor Gonadarche") + abline(lm(sem2_extract_vars[,"gonadal_sr"] ~ sem2_extract_vars[,"bio_gonadal"])) + 
  text(x=0.1, y=-0.8, labels = bquote(italic(R)^2 == .(format(sem2_g_bio_sr_r2))))

```


```{r save and export}
# Fit measures
fitmea_sr <- data.frame(fitmea_sr1_pml, fitmea_sr2_pml, fitmea_sr3_pml,
                         fitmea_sr4_pml)
fitmea_hm <- data.frame(fitmea_hm1v2_pml, fitmea_hm2v2_pml, fitmea_hm3v2_pml,
                         fitmea_hm4v2_pml)
fitmea_hsm <- data.frame(fitmea_hsm1_pml, fitmea_hsm2_pml)
fitmea_fm <- data.frame(fitmea_fm1v2_pml, fitmea_fm2v2_pml)
fitmea_sem <- data.frame(fitmea_sem1v2_pml, fitmea_sem2v2_pml)

# Save environment
save.image("Z:/dsnlab/TAG/projects/W1_puberty_modelling/Puberty_CFA_v2.RData")

```

